### ISSUE TITLE
registry-1.docker.io

### ISSUE THREAD

**Issue by sadaszewski** [davedoesdev/dxf#31]
No matter if I try with DXF_PASSWORD or DXF_TOKEN I can do neither dxf list-repos nor dxf list-aliases. I am getting an 'unauthorized' error each time. The credentials seem fine. Overall I have tried these two sets of environment variables:

DXF_HOST=registry-1.docker.io
DXF_USERNAME=myusername
DXF_PASSWORD=mypassword

or

DXF_HOST=registry-1.docker.io
DXF_USERNAME=myusername
DXF_TOKEN=mytoken

to no avail. Am I missing something obvious or is it a problem with registry-1.docker.io or dxf? I am trying to integrate dxf with https://github.com/sadaszewski/focker/ . It would be a great and impactful project with some help to get it off the ground. Thank you very much in advance.

**Comment by davedoesdev** [comment]
Hi @sadaszewski 

Thanks for raising this.

Does `test/module_example.py` work for you on a test repo? I just tried it against one of my repos and it worked. Just trying to narrow down where the problem is.

**Comment by davedoesdev** [comment]
@sadaszewski also, this works for me:

```
$ DXF_HOST=registry-1.docker.io dxf list-aliases davedoesdev/test
may15-readings
wup
```

without having to set `DXF_USERNAME` or `DXF_PASSWORD`. Does it work for you?

Note that `dxf list-repos` doesn't work on Docker Hub. I guess they don't want people listing every single repo on the system.

**Comment by davedoesdev** [comment]
@sadaszewski did you get a chance to try the above?

**Comment by davedoesdev** [comment]
@sadaszewski any updates on the above?

**Comment by sadaszewski** [comment]
Hi David,

Apologies for the hiatus. Let's forget about it for the moment, as I have
decided to keep the project limited to image building and container
composition, leaving image registry support out of it. Perhaps someone else
will pick this story up in the future. Thank you and sorry for the trouble.

Best regards,

--
Stanislaw

**Comment by davedoesdev** [comment]
@sadaszewski no problem! Thanks for raising a potential issue, I appreciate it.

**Comment by umdstu** [comment]
@davedoesdev 

I recently came across this and think I see what might be happening. At least in my case. 

Two component repos work fine, eg. `docker.io/curlimages/curl`, `docker.io/bitnami/python`, and `docker.io/circleci/openjdk` but 1 component repos fail to authenticate every time, eg. `docker.io/python`, `docker.io/openjdk` and `docker.io/eclipse-temurin`.

I was running 7.7.2, because pip refused to install 7.7.3 because of a dependency conflict, but ultimately got both installed and both fail to work for single component repos.

I poked around some and it looks like it may be how you're setting `_repo_path` or how authentication itself is being processed. Please let me know how I can help.

**Comment by davedoesdev** [comment]
Fixed in https://github.com/davedoesdev/dxf/commit/fa900a3533637ef7a669a128d4059b8ec09e024a thanks @umdstu
